import Koa from 'koa'
import cors from '@koa/cors'
import zodRouter from 'koa-zod-router'
import qs from 'koa-qs'
import { koaSwagger } from 'koa2-swagger-ui'
import { setupBookRoutes } from './src/books'
import { setupWarehouseRoutes } from './src/warehouse'
import swagger from './build/swagger.json'

const app = new Koa()

// We use koa-qs to enable parsing complex query strings, like our filters.
qs(app)

// And we add cors to ensure we can access our API from the mcmasterful-books website
app.use(cors())

const router = zodRouter({ zodRouter: { exposeRequestErrors: true } })

setupBookRoutes(router)
setupWarehouseRoutes(router)

app.use(router.routes())

app.use(koaSwagger({
  routePrefix: '/docs',
  specPrefix: '/docs/spec',
  exposeSpec: true,
  swaggerOptions: {
    spec: swagger // This object is an import of the swagger.json generated by tsoa
  }

}))

app.listen(3000, () => {
  console.log('listening!')
})
